version: 2

jobs:
  build:
    docker:
      - image: "debian:stretch"
    steps:
      - checkout
      - run:
          name: Installing SUDO
          command: 'apt-get update && apt-get install -y sudo && rm -rf /var/lib/apt/lists/*'
      - run:
          name: Installing GCC
          command: 'apt-get update && apt-get install -y gcc g++'
      - run:
          name: Install CMAKE
          command: 'apt-get update && sudo apt-get install -y cmake'
      - run:
          name: Creating Binary Files for RED
          command: 'mkdir -p build/RED; cd build/RED; cmake ../../src/RED; make; cd ../..'
      - run:
          name: Unit Testing for RED
          command: './bin/RED/testCases'
      - run:
          name: Creating Binary Files for WRED
          command: 'mkdir -p build/WRED; cd build/WRED; cmake ../../src/WRED; make; cd ../..'
      - run:
          name: Unit Testing for WRED
          command: './bin/WRED/testCases'
      - run:
          name: Creating Binary Files for taildrop
          command: 'mkdir -p build/taildrop; cd build/taildrop; cmake ../../src/taildrop; make; cd ../..'
      - run:
          name: Unit Testing for taildrop
          command: './bin/taildrop/testCases'
      - run:
          name: Creating Binary Files for RRED
          command: 'mkdir -p build/RRED; cd build/RRED; cmake ../../src/RRED; make; cd ../..'
      - run:
          name: Unit Testing for RRED
          command: './bin/RRED/testCases'